import frappe


LEGACY_WEB_PAGE_ROUTES = {
    "",
    "about",
    "about-modern",
    "Account_system",
    "all-products",
    "asset-management",
    "asset-management-modern",
    "attendance",
    "blog/artical",
    "blog/developer",
    "blog/erpnext",
    "blog/factories",
    "blog/financial",
    "blog/general-blog",
    "blog/hr",
    "blog/partner",
    "blog/real-state",
    "blog/stock",
    "blog-list",
    "blog-list-modern",
    "blog-post",
    "blog-post-modern",
    "cart",
    "catalog",
    "catalog-modern",
    "c4",
    "complete-solutions",
    "complete-solutions-modern",
    "computer-networks",
    "computer-networks-modern",
    "connect",
    "construction",
    "construction-management",
    "construction-management-modern",
    "construction-modern",
    "contact",
    "contact-modern",
    "crm",
    "crm-modern",
    "e-commerce",
    "expense-management",
    "factory",
    "factory-modern",
    "finance-management",
    "finance-management-modern",
    "home",
    "hr",
    "hr-modern",
    "hr2",
    "index-ar",
    "index-en",
    "int",
    "inventory-management",
    "inventory-management-modern",
    "jobs",
    "leave-management",
    "lms",
    "manufacturing-management",
    "manufacturing-management-modern",
    "pages/PageAR",
    "pages/PageEN",
    "pages/my-page-6487",
    "performance-management",
    "procurement-management",
    "procurement-management-modern",
    "project/PageAR",
    "rana",
    "recruitment",
    "register",
    "retais-erp",
    "rent-app",
    "rent-app-modern",
    "rental-companies",
    "rental-companies-modern",
    "retail-system",
    "retail-system-modern",
    "retailtest",
    "salary-payouts",
    "sales",
    "security-systems",
    "security-systems-modern",
    "ship",
    "shop-by-category",
    "solution-template",
    "solution-template-modern",
    "stock",
    "sub",
    "system",
    "system2",
    "tax-%26-benefits",
    "terms",
    "terms-modern",
    "test",
    "testabout",
    "testregister",
    "trade",
    "trade-modern",
    "web-development",
    "wells-solar",
    "wells-solar-modern",
}


def execute():
    if not frappe.db.table_exists("Web Page"):
        return

    routes = sorted(route.strip("/") for route in LEGACY_WEB_PAGE_ROUTES)
    web_pages = frappe.get_all(
        "Web Page",
        filters={"route": ["in", routes]},
        pluck="name",
        ignore_permissions=True,
    )

    for name in web_pages:
        frappe.delete_doc("Web Page", name, ignore_permissions=True, force=True)

    frappe.clear_cache()
