app_name = "c4web"
app_title = "C4 Web"
app_publisher = "Connect4systems"
app_description = "Connect4systems support app. Public website pages are now served as a static site."
app_email = "info@connect4systems.com"
app_license = "MIT"
